// Code generated by tork. DO NOT EDIT.

package genfixtures

import "github.com/tork-go/orm"

// Alpha is the row type of the alphas table.
type Alpha struct {
	ID      int  `db:"id"`
	BetaID  *int `db:"beta_id"`
	GammaID *int `db:"gamma_id"`

	Beta  *Beta
	Pal   *Beta
	Gamma *Gamma
}

// AlphaModel declares the alphas table.
type AlphaModel struct {
	orm.Table[Alpha]
	ID      *orm.IntColumn
	BetaID  *orm.NullableIntColumn
	GammaID *orm.NullableIntColumn
	Beta    orm.BelongsTo[Beta]
	Pal     orm.HasOne[Beta]
	Gamma   orm.BelongsTo[Gamma]
}

// Relations implements orm.Relater, naming every key explicitly
// so nothing is left to inference.
func (m *AlphaModel) Relations() []orm.RelationDef {
	return []orm.RelationDef{
		orm.Via(&m.Beta, m.BetaID),
		orm.Via(&m.Pal, Betas.AlphaID),
		orm.Via(&m.Gamma, m.GammaID),
	}
}

// Alphas is the alphas table.
var Alphas = orm.DefineTable[Alpha]("alphas", func(t *orm.TableBuilder[Alpha]) *AlphaModel {
	return &AlphaModel{
		Table:   t.Table(),
		ID:      t.Int("id").PrimaryKey(),
		BetaID:  t.NullableInt("beta_id").ReferencesTable("betas", "id"),
		GammaID: t.NullableInt("gamma_id").ReferencesTable("gammas", "id"),
	}
})
