// Code generated by tork. DO NOT EDIT.

package genfixtures

import (
	"time"

	"github.com/tork-go/orm"
)

// Author writes documents.
type Author struct {
	ID        int        `db:"id"`
	Name      string     `db:"name"`
	Rating    *float64   `db:"rating"`
	Tags      []string   `db:"tags"`
	Scores    *[]int     `db:"scores"`
	Meta      *Meta      `db:"meta"`
	Nonce     string     `db:"nonce"`
	CreatedAt time.Time  `db:"created_at"`
	DeletedAt *time.Time `db:"deleted_at"`

	Docs []Doc
}

// AuthorModel declares the authors table.
type AuthorModel struct {
	orm.Table[Author]
	ID        *orm.IntColumn
	Name      *orm.StringColumn
	Rating    *orm.NullableDoubleColumn
	Tags      *orm.StringArrayColumn
	Scores    *orm.NullableIntArrayColumn
	Meta      *orm.NullableJSONColumn[Meta]
	Nonce     *orm.StringColumn
	CreatedAt *orm.TimeColumn
	DeletedAt *orm.NullableTimeColumn
	Docs      orm.HasMany[Doc]
}

// Indexes implements orm.Indexer.
func (m *AuthorModel) Indexes() []orm.IndexDef {
	return []orm.IndexDef{
		orm.NewIndexDef(m.Name, m.CreatedAt).Where("deleted_at IS NULL").Named("idx_authors_name_created"),
		orm.NewIndexDef().On("lower(name)").Named("idx_authors_lower_name"),
	}
}

// Checks implements orm.Checker.
func (m *AuthorModel) Checks() []orm.CheckDef {
	return []orm.CheckDef{
		orm.NewCheckDef("rating IS NULL OR rating >= 0").Named("ck_author_rating"),
	}
}

// Relations implements orm.Relater, naming every key explicitly
// so nothing is left to inference.
func (m *AuthorModel) Relations() []orm.RelationDef {
	return []orm.RelationDef{
		orm.Via(&m.Docs, Documents.AuthorID),
	}
}

// Authors is the authors table.
var Authors = orm.DefineTable[Author]("authors", func(t *orm.TableBuilder[Author]) *AuthorModel {
	return &AuthorModel{
		Table:     t.Table(),
		ID:        t.Int("id").PrimaryKey(),
		Name:      t.String("name").Unique().NotNull().MaxLen(80),
		Rating:    t.NullableDouble("rating"),
		Tags:      t.StringArray("tags").NotNull().MaxLen(20),
		Scores:    t.NullableIntArray("scores"),
		Meta:      orm.NewNullableJSONColumn[Meta]("meta"),
		Nonce:     t.String("nonce").NotNull().GeneratedByClient(NewNonce),
		CreatedAt: t.Time("created_at").NotNull().ServerDefault("now()"),
		DeletedAt: t.NullableTime("deleted_at").SoftDelete(),
	}
})
