// Code generated by tork. DO NOT EDIT.

package genfixtures

import "github.com/tork-go/orm"

// Beta is the row type of the betas table.
type Beta struct {
	ID      int  `db:"id"`
	AlphaID *int `db:"alpha_id"`
	GammaID *int `db:"gamma_id"`

	Alpha  *Alpha
	Fans   []Alpha
	Gamma  *Gamma
	Gammas []Gamma
}

// BetaModel declares the betas table.
type BetaModel struct {
	orm.Table[Beta]
	ID      *orm.IntColumn
	AlphaID *orm.NullableIntColumn
	GammaID *orm.NullableIntColumn
	Alpha   orm.BelongsTo[Alpha]
	Fans    orm.HasMany[Alpha]
	Gamma   orm.BelongsTo[Gamma]
	Gammas  orm.HasMany[Gamma]
}

// Relations implements orm.Relater, naming every key explicitly
// so nothing is left to inference.
func (m *BetaModel) Relations() []orm.RelationDef {
	return []orm.RelationDef{
		orm.Via(&m.Alpha, m.AlphaID),
		orm.Via(&m.Fans, Alphas.BetaID),
		orm.Via(&m.Gamma, m.GammaID),
		orm.Via(&m.Gammas, Gammas.BetaID),
	}
}

// Betas is the betas table.
var Betas = orm.DefineTable[Beta]("betas", func(t *orm.TableBuilder[Beta]) *BetaModel {
	return &BetaModel{
		Table:   t.Table(),
		ID:      t.Int("id").PrimaryKey(),
		AlphaID: t.NullableInt("alpha_id").References(Alphas.ID),
		GammaID: t.NullableInt("gamma_id").ReferencesTable("gammas", "id"),
	}
})
