// Code generated by tork. DO NOT EDIT.

package genfixtures

import (
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"github.com/tork-go/orm"
)

// Doc is the row type of the documents table.
type Doc struct {
	ID       int             `db:"id"`
	Title    string          `db:"title"`
	Body     string          `db:"body"`
	Status   string          `db:"status"`
	Price    decimal.Decimal `db:"price"`
	Key      uuid.UUID       `db:"key"`
	Blob     Meta            `db:"blob"`
	AuthorID int             `db:"author_id"`
	ParentID *int            `db:"parent_id"`

	Author   *Author
	Parent   *Doc
	Children []Doc
	Labels   []Label
}

// DocModel declares the documents table.
type DocModel struct {
	orm.Table[Doc]
	ID       *orm.IntColumn
	Title    *orm.StringColumn
	Body     *orm.StringColumn
	Status   *orm.EnumColumn
	Price    *orm.DecimalColumn
	Key      *orm.UUIDColumn
	Blob     *orm.JSONColumn[Meta]
	AuthorID *orm.IntColumn
	ParentID *orm.NullableIntColumn
	Author   orm.BelongsTo[Author]
	Parent   orm.BelongsTo[Doc]
	Children orm.HasMany[Doc]
	Labels   orm.ManyToMany[Label]
}

// Indexes implements orm.Indexer.
func (m *DocModel) Indexes() []orm.IndexDef {
	return []orm.IndexDef{
		orm.NewIndexDef(m.Title, m.AuthorID).Unique().Named("u_docs_title_author"),
	}
}

// Relations implements orm.Relater, naming every key explicitly
// so nothing is left to inference.
func (m *DocModel) Relations() []orm.RelationDef {
	return []orm.RelationDef{
		orm.Via(&m.Author, m.AuthorID),
		orm.Via(&m.Parent, m.ParentID),
		orm.Via(&m.Children, Documents.ParentID),
		orm.Through(&m.Labels, DocLabels.DocID, DocLabels.LabelID),
	}
}

// Documents is the documents table.
var Documents = orm.DefineTable[Doc]("documents", func(t *orm.TableBuilder[Doc]) *DocModel {
	id := t.Int("id").PrimaryKey()
	return &DocModel{
		Table:    t.Table(),
		ID:       id,
		Title:    t.String("title").NotNull().MaxLen(120),
		Body:     t.String("body").NotNull(),
		Status:   t.Enum("status", "doc_status", "draft", "published").NotNull().ServerDefault("'draft'"),
		Price:    t.Decimal("price").NotNull().Numeric(10, 2).ServerDefault("0"),
		Key:      t.UUID("key").Unique().NotNull().GeneratedByClient(uuid.New),
		Blob:     orm.NewJSONColumn[Meta]("blob").NotNull().JSON(),
		AuthorID: t.Int("author_id").NotNull().References(Authors.ID).OnDelete(orm.ActionCascade).OnUpdate(orm.ActionRestrict),
		ParentID: t.NullableInt("parent_id").References(id),
	}
})
