// Code generated by tork. DO NOT EDIT.

package genfixtures

import "github.com/tork-go/orm"

// DocLabel is the row type of the doc_labels table.
type DocLabel struct {
	DocID   int `db:"doc_id"`
	LabelID int `db:"label_id"`

	Doc   *Doc
	Label *Label
}

// DocLabelModel declares the doc_labels table.
type DocLabelModel struct {
	orm.Table[DocLabel]
	DocID   *orm.IntColumn
	LabelID *orm.IntColumn
	Doc     orm.BelongsTo[Doc]
	Label   orm.BelongsTo[Label]
}

// Relations implements orm.Relater, naming every key explicitly
// so nothing is left to inference.
func (m *DocLabelModel) Relations() []orm.RelationDef {
	return []orm.RelationDef{
		orm.Via(&m.Doc, m.DocID),
		orm.Via(&m.Label, m.LabelID),
	}
}

// DocLabels is the doc_labels table.
var DocLabels = orm.DefineTable[DocLabel]("doc_labels", func(t *orm.TableBuilder[DocLabel]) *DocLabelModel {
	return &DocLabelModel{
		Table:   t.Table(),
		DocID:   t.Int("doc_id").PrimaryKey().References(Documents.ID).OnDelete(orm.ActionCascade),
		LabelID: t.Int("label_id").PrimaryKey().References(Labels.ID).OnDelete(orm.ActionCascade),
	}
})
