// Code generated by tork. DO NOT EDIT.

package genfixtures

import "github.com/tork-go/orm"

// Gamma closes a second path from Alpha back to Beta, so the cycle
// search meets a model it has already visited.
type Gamma struct {
	ID      int  `db:"id"`
	BetaID  *int `db:"beta_id"`
	OwnerID *int `db:"owner_id"`

	Beta   *Beta
	Alphas []Alpha
	Betas  []Beta
	Pals   []Gamma
	Owner  *Gamma
}

// GammaModel declares the gammas table.
type GammaModel struct {
	orm.Table[Gamma]
	ID      *orm.IntColumn
	BetaID  *orm.NullableIntColumn
	OwnerID *orm.NullableIntColumn
	Beta    orm.BelongsTo[Beta]
	Alphas  orm.HasMany[Alpha]
	Betas   orm.HasMany[Beta]
	Pals    orm.HasMany[Gamma]
	Owner   orm.BelongsTo[Gamma]
}

// Relations implements orm.Relater, naming every key explicitly
// so nothing is left to inference.
func (m *GammaModel) Relations() []orm.RelationDef {
	return []orm.RelationDef{
		orm.Via(&m.Beta, m.BetaID),
		orm.Via(&m.Alphas, Alphas.GammaID),
		orm.Via(&m.Betas, Betas.GammaID),
		orm.Via(&m.Pals, Gammas.OwnerID),
		orm.Via(&m.Owner, m.OwnerID),
	}
}

// Gammas is the gammas table.
var Gammas = orm.DefineTable[Gamma]("gammas", func(t *orm.TableBuilder[Gamma]) *GammaModel {
	id := t.Int("id").PrimaryKey()
	return &GammaModel{
		Table:   t.Table(),
		ID:      id,
		BetaID:  t.NullableInt("beta_id").References(Betas.ID),
		OwnerID: t.NullableInt("owner_id").References(id),
	}
})
