// Code generated by tork. DO NOT EDIT.

package genfixtures

import "github.com/tork-go/orm"

// Label is the row type of the labels table.
type Label struct {
	ID   int     `db:"id"`
	Name string  `db:"name"`
	Code *string `db:"code"`

	Docs []Doc
	Refs []Ref
}

// LabelModel declares the labels table.
type LabelModel struct {
	orm.Table[Label]
	ID   *orm.IntColumn
	Name *orm.StringColumn
	Code *orm.NullableStringColumn
	Docs orm.ManyToMany[Doc]
	Refs orm.HasMany[Ref]
}

// Relations implements orm.Relater, naming every key explicitly
// so nothing is left to inference.
func (m *LabelModel) Relations() []orm.RelationDef {
	return []orm.RelationDef{
		orm.Through(&m.Docs, DocLabels.LabelID, DocLabels.DocID),
		orm.Via(&m.Refs, Refs.LabelCode),
	}
}

// Labels is the labels table.
var Labels = orm.DefineTable[Label]("labels", func(t *orm.TableBuilder[Label]) *LabelModel {
	return &LabelModel{
		Table: t.Table(),
		ID:    t.Int("id").PrimaryKey(),
		Name:  t.String("name").Unique().NotNull(),
		Code:  t.NullableString("code").Unique(),
	}
})
