// Code generated by tork. DO NOT EDIT.

package genfixtures

import "github.com/tork-go/orm"

// Node keeps a composite key it also points at, which puts a self
// referencing composite foreign key in the ForeignKeys method, and a
// column literally named t, which cannot shadow the builder parameter.
type Node struct {
	T       int  `db:"t"`
	U       int  `db:"u"`
	ParentT *int `db:"parent_t"`
	ParentU *int `db:"parent_u"`

	Parent   *Node
	Children []Node
}

// NodeModel declares the nodes table.
type NodeModel struct {
	orm.Table[Node]
	T        *orm.IntColumn
	U        *orm.IntColumn
	ParentT  *orm.NullableIntColumn
	ParentU  *orm.NullableIntColumn
	Parent   orm.BelongsTo[Node]
	Children orm.HasMany[Node]
}

// ForeignKeys implements orm.ForeignKeyer.
func (m *NodeModel) ForeignKeys() []orm.ForeignKeyDef {
	return []orm.ForeignKeyDef{
		orm.NewForeignKeyDef(m.ParentT, m.ParentU).References(m.T, m.U).OnDelete(orm.ActionCascade).OnUpdate(orm.ActionCascade).Named("fk_nodes_parent"),
	}
}

// Relations implements orm.Relater, naming every key explicitly
// so nothing is left to inference.
func (m *NodeModel) Relations() []orm.RelationDef {
	return []orm.RelationDef{
		orm.Via(&m.Parent, m.ParentT),
		orm.Via(&m.Children, Nodes.ParentT),
	}
}

// Nodes is the nodes table.
var Nodes = orm.DefineTable[Node]("nodes", func(t *orm.TableBuilder[Node]) *NodeModel {
	return &NodeModel{
		Table:   t.Table(),
		T:       t.Int("t").PrimaryKey(),
		U:       t.Int("u").PrimaryKey(),
		ParentT: t.NullableInt("parent_t"),
		ParentU: t.NullableInt("parent_u"),
	}
})
