// Code generated by tork. DO NOT EDIT.

package genfixtures

import "github.com/tork-go/orm"

// Pair is the row type of the pairs table.
type Pair struct {
	A int `db:"a"`
	B int `db:"b"`

	Other *Ref
}

// PairModel declares the pairs table.
type PairModel struct {
	orm.Table[Pair]
	A     *orm.IntColumn
	B     *orm.IntColumn
	Other orm.HasOne[Ref]
}

// Relations implements orm.Relater, naming every key explicitly
// so nothing is left to inference.
func (m *PairModel) Relations() []orm.RelationDef {
	return []orm.RelationDef{
		orm.Via(&m.Other, Refs.Pa),
	}
}

// Pairs is the pairs table.
var Pairs = orm.DefineTable[Pair]("pairs", func(t *orm.TableBuilder[Pair]) *PairModel {
	return &PairModel{
		Table: t.Table(),
		A:     t.Int("a").PrimaryKey(),
		B:     t.Int("b").PrimaryKey(),
	}
})
