// Code generated by tork. DO NOT EDIT.

package genfixtures

import "github.com/tork-go/orm"

// Ref is the row type of the refs table.
type Ref struct {
	ID        int     `db:"id"`
	Pa        *int    `db:"pa"`
	Pb        *int    `db:"pb"`
	LabelCode *string `db:"label_code"`

	Pair  *Pair
	Label *Label
}

// RefModel declares the refs table.
type RefModel struct {
	orm.Table[Ref]
	ID        *orm.IntColumn
	Pa        *orm.NullableIntColumn
	Pb        *orm.NullableIntColumn
	LabelCode *orm.NullableStringColumn
	Pair      orm.BelongsTo[Pair]
	Label     orm.BelongsTo[Label]
}

// ForeignKeys implements orm.ForeignKeyer.
func (m *RefModel) ForeignKeys() []orm.ForeignKeyDef {
	return []orm.ForeignKeyDef{
		orm.NewForeignKeyDef(m.Pa, m.Pb).References(Pairs.A, Pairs.B).OnDelete(orm.ActionSetNull).Named("fk_ref_pair"),
	}
}

// Relations implements orm.Relater, naming every key explicitly
// so nothing is left to inference.
func (m *RefModel) Relations() []orm.RelationDef {
	return []orm.RelationDef{
		orm.Via(&m.Pair, m.Pa),
		orm.Via(&m.Label, m.LabelCode),
	}
}

// Refs is the refs table.
var Refs = orm.DefineTable[Ref]("refs", func(t *orm.TableBuilder[Ref]) *RefModel {
	return &RefModel{
		Table:     t.Table(),
		ID:        t.Int("id").PrimaryKey(),
		Pa:        t.NullableInt("pa"),
		Pb:        t.NullableInt("pb"),
		LabelCode: t.NullableString("label_code").ReferencesTable("labels", "code"),
	}
})
