// Code generated by tork. DO NOT EDIT.

package genfixtures

import "github.com/tork-go/orm"

// AllModels lists every generated model in name order, ready to
// hand straight to migrations:
//
//	cli.Run(dsn, "migrations", genfixtures.AllModels()...)
func AllModels() []orm.Model {
	return []orm.Model{
		Alphas,
		Authors,
		Betas,
		Documents,
		DocLabels,
		Gammas,
		Labels,
		Nodes,
		Pairs,
		Refs,
		Slots,
	}
}
