// Code generated by tork. DO NOT EDIT.

package genfixtures

import "github.com/tork-go/orm"

// Slot names its key t, which is exactly what the builder parameter
// is called, so the hoisted local has to step aside.
type Slot struct {
	T       int  `db:"t"`
	ParentT *int `db:"parent_t"`

	Parent *Slot
	Kids   []Slot
}

// SlotModel declares the slots table.
type SlotModel struct {
	orm.Table[Slot]
	T       *orm.IntColumn
	ParentT *orm.NullableIntColumn
	Parent  orm.BelongsTo[Slot]
	Kids    orm.HasMany[Slot]
}

// Relations implements orm.Relater, naming every key explicitly
// so nothing is left to inference.
func (m *SlotModel) Relations() []orm.RelationDef {
	return []orm.RelationDef{
		orm.Via(&m.Parent, m.ParentT),
		orm.Via(&m.Kids, Slots.ParentT),
	}
}

// Slots is the slots table.
var Slots = orm.DefineTable[Slot]("slots", func(t *orm.TableBuilder[Slot]) *SlotModel {
	t_ := t.Int("t").PrimaryKey()
	return &SlotModel{
		Table:   t.Table(),
		T:       t_,
		ParentT: t.NullableInt("parent_t").References(t_),
	}
})
