package migrate

import (
	"slices"
	"sort"
	"strings"

	"github.com/tork-go/orm/schema"
)

// Diff compares current against desired and returns the operations that
// transform current into desired, in an order safe to run against a real
// database: everything that could block a drop is dropped first (foreign
// keys, then unique constraints, then indexes, then primary keys, then
// columns, then tables), then new tables are created, then everything is
// added back (columns, altered types and nullability, primary keys,
// indexes, unique constraints, and finally foreign keys, once every table
// and column they reference is guaranteed to exist).
//
// Down-migration SQL is generated by calling Diff(desired, current), the
// same function with its arguments swapped, rather than a separate
// "invert this operation" function: since Diff only looks at structural
// differences and the phase order above is self-consistent either
// direction, this produces a correctly ordered undo for free.
//
// Tables and columns are matched by exact name. A renamed column is not
// detected: it produces a DropColumn plus an AddColumn, the same
// limitation every autogenerate tool documents.
//
// Primary key, unique, and foreign key constraints are matched by their
// column set, not by name, so a live constraint that already covers the
// desired columns (even with a different, e.g. database-generated, name)
// is left alone.
func Diff(current, desired schema.Schema) []Operation {
	curByName := tablesByName(current.Tables)
	desByName := tablesByName(desired.Tables)

	var (
		dropFKs, dropUniques, dropIndexes, dropPKs, dropCols, dropTables []Operation
		createTables, addCols, alterTypes, alterNulls                    []Operation
		addPKs, addIndexes, addUniques, addFKs                           []Operation
	)

	for _, cur := range current.Tables {
		des, ok := desByName[cur.Name]
		if !ok {
			for _, fk := range cur.ForeignKeys {
				dropFKs = append(dropFKs, DropForeignKey{Table: cur.Name, Name: fk.Name})
			}
			dropTables = append(dropTables, DropTable{Table: cur.Name})
			continue
		}
		td := diffTable(cur.Name, cur, des)
		dropFKs = append(dropFKs, td.dropFKs...)
		dropUniques = append(dropUniques, td.dropUniques...)
		dropIndexes = append(dropIndexes, td.dropIndexes...)
		dropPKs = append(dropPKs, td.dropPKs...)
		dropCols = append(dropCols, td.dropCols...)
		addCols = append(addCols, td.addCols...)
		alterTypes = append(alterTypes, td.alterTypes...)
		alterNulls = append(alterNulls, td.alterNulls...)
		addPKs = append(addPKs, td.addPKs...)
		addIndexes = append(addIndexes, td.addIndexes...)
		addUniques = append(addUniques, td.addUniques...)
		addFKs = append(addFKs, td.addFKs...)
	}

	for _, des := range desired.Tables {
		if _, ok := curByName[des.Name]; ok {
			continue
		}
		// Foreign keys are never inlined into CreateTable, even for a
		// brand-new table: every foreign key is added separately, in the
		// last phase, once all new tables already exist. This handles
		// circular and self-referencing foreign keys between new tables
		// uniformly, with no dependency-cycle detection needed. A plain
		// index structurally can't be inlined into CREATE TABLE in
		// Postgres at all, so it's stripped and re-emitted the same way.
		t := des
		t.ForeignKeys = nil
		t.Indexes = nil
		createTables = append(createTables, CreateTable{Table: t})
		for _, fk := range des.ForeignKeys {
			addFKs = append(addFKs, AddForeignKey{Table: des.Name, ForeignKey: fk})
		}
		for _, ix := range des.Indexes {
			addIndexes = append(addIndexes, AddIndex{Table: des.Name, Index: ix})
		}
	}

	phases := [][]Operation{
		dropFKs, dropUniques, dropIndexes, dropPKs, dropCols, dropTables,
		createTables, addCols, alterTypes, alterNulls,
		addPKs, addIndexes, addUniques, addFKs,
	}
	var ops []Operation
	for _, phase := range phases {
		sortOps(phase)
		ops = append(ops, phase...)
	}
	return ops
}

type tableDiff struct {
	dropFKs, dropUniques, dropIndexes, dropPKs, dropCols []Operation
	addCols, alterTypes, alterNulls                      []Operation
	addPKs, addIndexes, addUniques, addFKs               []Operation
}

func diffTable(name string, cur, des schema.Table) tableDiff {
	var td tableDiff

	curCols := columnsByName(cur.Columns)
	desCols := columnsByName(des.Columns)

	for _, c := range cur.Columns {
		if _, ok := desCols[c.Name]; !ok {
			td.dropCols = append(td.dropCols, DropColumn{Table: name, Column: c.Name})
		}
	}
	for _, dc := range des.Columns {
		cc, ok := curCols[dc.Name]
		if !ok {
			td.addCols = append(td.addCols, AddColumn{Table: name, Column: dc})
			continue
		}
		if !cc.Type.Equal(dc.Type) {
			td.alterTypes = append(td.alterTypes, AlterColumnType{Table: name, Column: dc})
		}
		if cc.NotNull != dc.NotNull {
			td.alterNulls = append(td.alterNulls, AlterColumnNullability{Table: name, Column: dc.Name, NotNull: dc.NotNull})
		}
	}

	switch {
	case cur.PrimaryKey == nil && des.PrimaryKey != nil:
		td.addPKs = append(td.addPKs, AddPrimaryKey{Table: name, PrimaryKey: *des.PrimaryKey})
	case cur.PrimaryKey != nil && des.PrimaryKey == nil:
		td.dropPKs = append(td.dropPKs, DropPrimaryKey{Table: name, Name: cur.PrimaryKey.Name})
	case cur.PrimaryKey != nil && des.PrimaryKey != nil:
		if !slices.Equal(cur.PrimaryKey.Columns, des.PrimaryKey.Columns) {
			td.dropPKs = append(td.dropPKs, DropPrimaryKey{Table: name, Name: cur.PrimaryKey.Name})
			td.addPKs = append(td.addPKs, AddPrimaryKey{Table: name, PrimaryKey: *des.PrimaryKey})
		}
	}

	curUniques := byColumnKey(cur.Uniques, func(u schema.UniqueConstraint) []string { return u.Columns })
	desUniques := byColumnKey(des.Uniques, func(u schema.UniqueConstraint) []string { return u.Columns })
	for _, u := range cur.Uniques {
		if _, ok := desUniques[columnKey(u.Columns)]; !ok {
			td.dropUniques = append(td.dropUniques, DropUnique{Table: name, Name: u.Name})
		}
	}
	for _, u := range des.Uniques {
		if _, ok := curUniques[columnKey(u.Columns)]; !ok {
			td.addUniques = append(td.addUniques, AddUnique{Table: name, Unique: u})
		}
	}

	curIndexes := byColumnKey(cur.Indexes, func(ix schema.Index) []string { return ix.Columns })
	desIndexes := byColumnKey(des.Indexes, func(ix schema.Index) []string { return ix.Columns })
	for _, ix := range cur.Indexes {
		if _, ok := desIndexes[columnKey(ix.Columns)]; !ok {
			td.dropIndexes = append(td.dropIndexes, DropIndex{Table: name, Name: ix.Name})
		}
	}
	for _, ix := range des.Indexes {
		if _, ok := curIndexes[columnKey(ix.Columns)]; !ok {
			td.addIndexes = append(td.addIndexes, AddIndex{Table: name, Index: ix})
		}
	}

	curFKs := byColumnKey(cur.ForeignKeys, func(fk schema.ForeignKey) []string { return fk.Columns })
	desFKs := byColumnKey(des.ForeignKeys, func(fk schema.ForeignKey) []string { return fk.Columns })
	for _, fk := range cur.ForeignKeys {
		if _, ok := desFKs[columnKey(fk.Columns)]; !ok {
			td.dropFKs = append(td.dropFKs, DropForeignKey{Table: name, Name: fk.Name})
		}
	}
	for _, fk := range des.ForeignKeys {
		if _, ok := curFKs[columnKey(fk.Columns)]; !ok {
			td.addFKs = append(td.addFKs, AddForeignKey{Table: name, ForeignKey: fk})
		}
	}

	return td
}

func tablesByName(tables []schema.Table) map[string]schema.Table {
	m := make(map[string]schema.Table, len(tables))
	for _, t := range tables {
		m[t.Name] = t
	}
	return m
}

func columnsByName(cols []schema.Column) map[string]schema.Column {
	m := make(map[string]schema.Column, len(cols))
	for _, c := range cols {
		m[c.Name] = c
	}
	return m
}

// columnKey turns an ordered column list into a map key. Column order is
// significant: UNIQUE (a, b) and UNIQUE (b, a) are treated as distinct
// constraints, matching how they're named and rendered.
func columnKey(columns []string) string {
	return strings.Join(columns, "\x00")
}

func byColumnKey[T any](items []T, columns func(T) []string) map[string]T {
	m := make(map[string]T, len(items))
	for _, item := range items {
		m[columnKey(columns(item))] = item
	}
	return m
}

// sortKey extracts the (table, secondary) key used to order operations
// within a phase, for reproducible output.
func sortKey(op Operation) (table, secondary string) {
	switch o := op.(type) {
	case CreateTable:
		return o.Table.Name, ""
	case DropTable:
		return o.Table, ""
	case AddColumn:
		return o.Table, o.Column.Name
	case DropColumn:
		return o.Table, o.Column
	case AlterColumnType:
		return o.Table, o.Column.Name
	case AlterColumnNullability:
		return o.Table, o.Column
	case AddPrimaryKey:
		return o.Table, o.PrimaryKey.Name
	case DropPrimaryKey:
		return o.Table, o.Name
	case AddUnique:
		return o.Table, o.Unique.Name
	case DropUnique:
		return o.Table, o.Name
	case AddIndex:
		return o.Table, o.Index.Name
	case DropIndex:
		return o.Table, o.Name
	case AddForeignKey:
		return o.Table, o.ForeignKey.Name
	case DropForeignKey:
		return o.Table, o.Name
	default:
		return "", ""
	}
}

func sortOps(ops []Operation) {
	sort.SliceStable(ops, func(i, j int) bool {
		ti, si := sortKey(ops[i])
		tj, sj := sortKey(ops[j])
		if ti != tj {
			return ti < tj
		}
		return si < sj
	})
}
