package migrate

import (
	"fmt"
	"slices"
	"sort"
	"strings"

	"github.com/tork-go/orm/schema"
)

// Diff compares current against desired and returns the operations that
// transform current into desired, in an order safe to run against a real
// database: everything that could block a drop is dropped first (foreign
// keys, then unique constraints, then check constraints, then indexes,
// then primary keys, then columns, then tables, then enum types), then new
// enum types and tables are created, then everything is added back
// (columns, altered types and nullability, primary keys, indexes, check
// constraints, unique constraints, and finally foreign keys, once every
// table and column they reference is guaranteed to exist).
//
// Down-migration SQL is generated by calling Diff(desired, current), the
// same function with its arguments swapped, rather than a separate
// "invert this operation" function: since Diff only looks at structural
// differences and the phase order above is self-consistent either
// direction, this produces a correctly ordered undo for free.
//
// Tables and columns are matched by exact name. A renamed column is not
// detected: it produces a DropColumn plus an AddColumn, the same
// limitation every autogenerate tool documents.
//
// Primary key, unique, index, and foreign key constraints are matched by
// their column set, not by name, so a live constraint that already covers
// the desired columns (even with a different, e.g. database-generated,
// name) is left alone. A CHECK constraint has no natural column set to
// match by, so it's matched by name instead; see diffTable.
//
// Diff returns an error only when an enum type's value list can't be
// migrated: Postgres allows appending an enum value but not removing or
// reordering one without recreating the type, so a non-additive change is
// a hard error in both directions, not a silently degraded operation.
func Diff(current, desired schema.Schema) ([]Operation, error) {
	curByName := tablesByName(current.Tables)
	desByName := tablesByName(desired.Tables)

	createEnumTypes, addEnumValues, dropEnumTypes, err := diffEnumTypes(current.EnumTypes, desired.EnumTypes)
	if err != nil {
		return nil, err
	}

	var (
		dropFKs, dropUniques, dropChecks, dropIndexes, dropPKs, dropCols, dropTables []Operation
		createTables, addCols, alterTypes, alterNulls, alterDefaults                 []Operation
		addPKs, addIndexes, addChecks, addUniques, addFKs                            []Operation
	)

	for _, cur := range current.Tables {
		des, ok := desByName[cur.Name]
		if !ok {
			for _, fk := range cur.ForeignKeys {
				dropFKs = append(dropFKs, DropForeignKey{Table: cur.Name, Name: fk.Name})
			}
			dropTables = append(dropTables, DropTable{Table: cur.Name})
			continue
		}
		td := diffTable(cur.Name, cur, des)
		dropFKs = append(dropFKs, td.dropFKs...)
		dropUniques = append(dropUniques, td.dropUniques...)
		dropChecks = append(dropChecks, td.dropChecks...)
		dropIndexes = append(dropIndexes, td.dropIndexes...)
		dropPKs = append(dropPKs, td.dropPKs...)
		dropCols = append(dropCols, td.dropCols...)
		addCols = append(addCols, td.addCols...)
		alterTypes = append(alterTypes, td.alterTypes...)
		alterNulls = append(alterNulls, td.alterNulls...)
		alterDefaults = append(alterDefaults, td.alterDefaults...)
		addPKs = append(addPKs, td.addPKs...)
		addIndexes = append(addIndexes, td.addIndexes...)
		addChecks = append(addChecks, td.addChecks...)
		addUniques = append(addUniques, td.addUniques...)
		addFKs = append(addFKs, td.addFKs...)
	}

	for _, des := range desired.Tables {
		if _, ok := curByName[des.Name]; ok {
			continue
		}
		// Foreign keys are never inlined into CreateTable, even for a
		// brand-new table: every foreign key is added separately, in the
		// last phase, once all new tables already exist. This handles
		// circular and self-referencing foreign keys between new tables
		// uniformly, with no dependency-cycle detection needed. A plain
		// index structurally can't be inlined into CREATE TABLE in
		// Postgres at all, so it's stripped and re-emitted the same way.
		t := des
		t.ForeignKeys = nil
		t.Indexes = nil
		createTables = append(createTables, CreateTable{Table: t})
		for _, fk := range des.ForeignKeys {
			addFKs = append(addFKs, AddForeignKey{Table: des.Name, ForeignKey: fk})
		}
		for _, ix := range des.Indexes {
			addIndexes = append(addIndexes, AddIndex{Table: des.Name, Index: ix})
		}
	}

	phases := [][]Operation{
		// drop side: most-depended-upon first
		dropFKs, dropUniques, dropChecks, dropIndexes, dropPKs, dropCols, dropTables, dropEnumTypes,
		// add side: exact reverse of the drop side
		createEnumTypes, addEnumValues, createTables, addCols, alterTypes, alterNulls,
		alterDefaults,
		addPKs, addIndexes, addChecks, addUniques, addFKs,
	}
	var ops []Operation
	for _, phase := range phases {
		sortOps(phase)
		ops = append(ops, phase...)
	}
	return ops, nil
}

// diffEnumTypes compares enum types schema-wide, not per-table, since a
// single enum type can be shared by columns across multiple tables. It
// must run before everything that can reference an enum type
// (CreateTable, AddColumn, AlterColumnType) and its drops must run after
// everything that stops referencing one, so its create/addValues and drop
// results are placed at the very start and very end of the phase list
// respectively, preserving the drop/add mirror symmetry.
func diffEnumTypes(current, desired []schema.EnumType) (create, addValues, drop []Operation, err error) {
	curByName := make(map[string]schema.EnumType, len(current))
	for _, e := range current {
		curByName[e.Name] = e
	}
	desByName := make(map[string]schema.EnumType, len(desired))
	for _, e := range desired {
		desByName[e.Name] = e
	}

	for _, e := range current {
		if _, ok := desByName[e.Name]; !ok {
			drop = append(drop, DropEnumType{Name: e.Name})
		}
	}
	for _, e := range desired {
		ce, ok := curByName[e.Name]
		if !ok {
			create = append(create, CreateEnumType{Enum: e})
			continue
		}
		ops, err := diffEnumValues(e.Name, ce.Values, e.Values)
		if err != nil {
			return nil, nil, nil, err
		}
		addValues = append(addValues, ops...)
	}
	return create, addValues, drop, nil
}

// diffEnumValues requires cur to be an order-preserving subsequence of
// des: every current value still present, in the same relative order. If
// not, the change isn't purely additive, and Postgres has no ALTER TYPE
// for removing or reordering an enum value without recreating the type,
// so this is a hard error in both diff directions, not just the
// down-pass. For a value inserted in the middle of the list (not just
// appended at the tail), the resulting AddEnumValue uses After set to its
// nearest preceding neighbor that's already established (originally in
// cur, or added earlier in this same result), or Before set to cur's
// first value when no such neighbor exists, so a mid-list insert
// round-trips to the correct position.
func diffEnumValues(name string, cur, des []string) ([]Operation, error) {
	if !isSubsequence(cur, des) {
		return nil, fmt.Errorf(
			"enum type %q: values %v cannot be migrated to %v: removing or reordering enum values isn't supported (Postgres requires recreating the type); values may only be appended",
			name, cur, des)
	}

	curSet := make(map[string]bool, len(cur))
	for _, v := range cur {
		curSet[v] = true
	}

	var ops []Operation
	lastEstablished := ""
	hasLast := false
	for _, v := range des {
		if curSet[v] {
			lastEstablished = v
			hasLast = true
			continue
		}
		op := AddEnumValue{Name: name, Value: v}
		switch {
		case hasLast:
			op.After = lastEstablished
		case len(cur) > 0:
			op.Before = cur[0]
		}
		ops = append(ops, op)
		lastEstablished = v
		hasLast = true
	}
	return ops, nil
}

// isSubsequence reports whether cur appears in des, in order, though not
// necessarily contiguously.
func isSubsequence(cur, des []string) bool {
	i := 0
	for _, v := range des {
		if i < len(cur) && cur[i] == v {
			i++
		}
	}
	return i == len(cur)
}

type tableDiff struct {
	dropFKs, dropUniques, dropChecks, dropIndexes, dropPKs, dropCols []Operation
	addCols, alterTypes, alterNulls, alterDefaults                   []Operation
	addPKs, addIndexes, addChecks, addUniques, addFKs                []Operation
}

func diffTable(name string, cur, des schema.Table) tableDiff {
	var td tableDiff

	curCols := columnsByName(cur.Columns)
	desCols := columnsByName(des.Columns)

	for _, c := range cur.Columns {
		if _, ok := desCols[c.Name]; !ok {
			td.dropCols = append(td.dropCols, DropColumn{Table: name, Column: c.Name})
		}
	}
	for _, dc := range des.Columns {
		cc, ok := curCols[dc.Name]
		if !ok {
			td.addCols = append(td.addCols, AddColumn{Table: name, Column: dc})
			continue
		}
		if !cc.Type.Equal(dc.Type) {
			td.alterTypes = append(td.alterTypes, AlterColumnType{Table: name, Column: dc})
		}
		if cc.NotNull != dc.NotNull {
			td.alterNulls = append(td.alterNulls, AlterColumnNullability{Table: name, Column: dc.Name, NotNull: dc.NotNull})
		}
		if !defaultsEquivalent(cc.ServerDefault, dc.ServerDefault) {
			td.alterDefaults = append(td.alterDefaults, AlterColumnDefault{
				Table: name, Column: dc.Name, Default: dc.ServerDefault,
			})
		}
	}

	switch {
	case cur.PrimaryKey == nil && des.PrimaryKey != nil:
		td.addPKs = append(td.addPKs, AddPrimaryKey{Table: name, PrimaryKey: *des.PrimaryKey})
	case cur.PrimaryKey != nil && des.PrimaryKey == nil:
		td.dropPKs = append(td.dropPKs, DropPrimaryKey{Table: name, Name: cur.PrimaryKey.Name})
	case cur.PrimaryKey != nil && des.PrimaryKey != nil:
		if !slices.Equal(cur.PrimaryKey.Columns, des.PrimaryKey.Columns) {
			td.dropPKs = append(td.dropPKs, DropPrimaryKey{Table: name, Name: cur.PrimaryKey.Name})
			td.addPKs = append(td.addPKs, AddPrimaryKey{Table: name, PrimaryKey: *des.PrimaryKey})
		}
	}

	curUniques := byColumnKey(cur.Uniques, func(u schema.UniqueConstraint) []string { return u.Columns })
	desUniques := byColumnKey(des.Uniques, func(u schema.UniqueConstraint) []string { return u.Columns })
	for _, u := range cur.Uniques {
		if _, ok := desUniques[columnKey(u.Columns)]; !ok {
			td.dropUniques = append(td.dropUniques, DropUnique{Table: name, Name: u.Name})
		}
	}
	for _, u := range des.Uniques {
		if _, ok := curUniques[columnKey(u.Columns)]; !ok {
			td.addUniques = append(td.addUniques, AddUnique{Table: name, Unique: u})
		}
	}

	curIndexes := byColumnKey(cur.Indexes, func(ix schema.Index) []string { return ix.Columns })
	desIndexes := byColumnKey(des.Indexes, func(ix schema.Index) []string { return ix.Columns })
	for _, ix := range cur.Indexes {
		if _, ok := desIndexes[columnKey(ix.Columns)]; !ok {
			td.dropIndexes = append(td.dropIndexes, DropIndex{Table: name, Name: ix.Name})
		}
	}
	for _, ix := range des.Indexes {
		if _, ok := curIndexes[columnKey(ix.Columns)]; !ok {
			td.addIndexes = append(td.addIndexes, AddIndex{Table: name, Index: ix})
		}
	}

	// A CHECK constraint has no natural column set (its expression can
	// reference any number of columns, or none), so it's matched by name
	// instead, with a best-effort normalized comparison of the expression
	// text tolerant of Postgres's own re-formatting. This can still
	// false-positive a "changed" constraint for some expression rewrites
	// (e.g. IN-lists rewritten to = ANY (ARRAY[...])); see
	// docs/2.fundamentals/4.constraints.md.
	curChecks := checksByName(cur.Checks)
	desChecks := checksByName(des.Checks)
	for _, c := range cur.Checks {
		dc, ok := desChecks[c.Name]
		if !ok || normalizeExpr(c.Expression) != normalizeExpr(dc.Expression) {
			td.dropChecks = append(td.dropChecks, DropCheck{Table: name, Name: c.Name})
		}
	}
	for _, c := range des.Checks {
		cc, ok := curChecks[c.Name]
		if !ok || normalizeExpr(cc.Expression) != normalizeExpr(c.Expression) {
			td.addChecks = append(td.addChecks, AddCheck{Table: name, Check: c})
		}
	}

	// FK matching is by column set, like PK/Unique/Index, but a mismatch
	// on OnDelete/OnUpdate for an otherwise-matched column set still
	// produces a drop+add pair: Postgres cannot ALTER a foreign key's
	// referential actions in place.
	curFKs := byColumnKey(cur.ForeignKeys, func(fk schema.ForeignKey) []string { return fk.Columns })
	desFKs := byColumnKey(des.ForeignKeys, func(fk schema.ForeignKey) []string { return fk.Columns })
	for _, fk := range cur.ForeignKeys {
		dfk, ok := desFKs[columnKey(fk.Columns)]
		if !ok || !fkActionsEqual(fk, dfk) {
			td.dropFKs = append(td.dropFKs, DropForeignKey{Table: name, Name: fk.Name})
		}
	}
	for _, fk := range des.ForeignKeys {
		cfk, ok := curFKs[columnKey(fk.Columns)]
		if !ok || !fkActionsEqual(cfk, fk) {
			td.addFKs = append(td.addFKs, AddForeignKey{Table: name, ForeignKey: fk})
		}
	}

	return td
}

func fkActionsEqual(a, b schema.ForeignKey) bool {
	return a.OnDelete == b.OnDelete && a.OnUpdate == b.OnUpdate
}

func tablesByName(tables []schema.Table) map[string]schema.Table {
	m := make(map[string]schema.Table, len(tables))
	for _, t := range tables {
		m[t.Name] = t
	}
	return m
}

func columnsByName(cols []schema.Column) map[string]schema.Column {
	m := make(map[string]schema.Column, len(cols))
	for _, c := range cols {
		m[c.Name] = c
	}
	return m
}

func checksByName(checks []schema.Check) map[string]schema.Check {
	m := make(map[string]schema.Check, len(checks))
	for _, c := range checks {
		m[c.Name] = c
	}
	return m
}

// columnKey turns an ordered column list into a map key. Column order is
// significant: UNIQUE (a, b) and UNIQUE (b, a) are treated as distinct
// constraints, matching how they're named and rendered.
func columnKey(columns []string) string {
	return strings.Join(columns, "\x00")
}

func byColumnKey[T any](items []T, columns func(T) []string) map[string]T {
	m := make(map[string]T, len(items))
	for _, item := range items {
		m[columnKey(columns(item))] = item
	}
	return m
}

// normalizeExpr does a best-effort comparison tolerant of Postgres's own
// re-formatting of a stored CHECK expression (collapsed whitespace, an
// added single layer of wrapping parens). It is NOT a SQL parser and will
// not catch more aggressive rewrites (e.g. IN-lists rewritten to
// = ANY (ARRAY[...])). See docs/2.fundamentals/4.constraints.md.
func normalizeExpr(s string) string {
	return unwrapOuterParens(strings.Join(strings.Fields(s), " "))
}

// unwrapOuterParens strips one layer of parentheses that wraps the entire
// expression, if present. It only strips when the leading '(' and
// trailing ')' are a genuinely matching pair (parens balance back to zero
// only at the very end), so "(a) AND (b)" is left alone rather than
// mangled.
func unwrapOuterParens(s string) string {
	if len(s) < 2 || s[0] != '(' || s[len(s)-1] != ')' {
		return s
	}
	depth := 0
	for i, r := range s {
		switch r {
		case '(':
			depth++
		case ')':
			depth--
			if depth == 0 && i != len(s)-1 {
				return s
			}
		}
	}
	return strings.TrimSpace(s[1 : len(s)-1])
}

// sortKey extracts the (table, secondary) key used to order operations
// within a phase, for reproducible output.
func sortKey(op Operation) (table, secondary string) {
	switch o := op.(type) {
	case CreateTable:
		return o.Table.Name, ""
	case DropTable:
		return o.Table, ""
	case AddColumn:
		return o.Table, o.Column.Name
	case DropColumn:
		return o.Table, o.Column
	case AlterColumnType:
		return o.Table, o.Column.Name
	case AlterColumnNullability:
		return o.Table, o.Column
	case AddPrimaryKey:
		return o.Table, o.PrimaryKey.Name
	case DropPrimaryKey:
		return o.Table, o.Name
	case AddUnique:
		return o.Table, o.Unique.Name
	case DropUnique:
		return o.Table, o.Name
	case AddIndex:
		return o.Table, o.Index.Name
	case DropIndex:
		return o.Table, o.Name
	case AddCheck:
		return o.Table, o.Check.Name
	case DropCheck:
		return o.Table, o.Name
	case AddForeignKey:
		return o.Table, o.ForeignKey.Name
	case DropForeignKey:
		return o.Table, o.Name
	case CreateEnumType:
		return o.Enum.Name, ""
	case DropEnumType:
		return o.Name, ""
	case AddEnumValue:
		return o.Name, o.Value
	default:
		return "", ""
	}
}

func sortOps(ops []Operation) {
	sort.SliceStable(ops, func(i, j int) bool {
		ti, si := sortKey(ops[i])
		tj, sj := sortKey(ops[j])
		if ti != tj {
			return ti < tj
		}
		return si < sj
	})
}

// defaultsEquivalent reports whether two DEFAULT expressions mean the same
// thing, one as a database reported it and one as a model declared it.
//
// It exists for the same reason normalizeExpr does for CHECK constraints:
// a database re-prints an expression from its parsed form rather than
// storing the text given, so comparing the two literally would have every
// migration after the first propose changing a default back to what it
// already is. That is why defaults went uncompared until now.
//
// Two differences matter in practice, and Postgres applies both while
// printing: a cast added to the whole expression, so 'draft' comes back as
// 'draft'::text, and parentheses around a call, so now()::text comes back
// as (now())::text. Both sides are normalised rather than just the
// introspected one, which is what a first attempt got wrong: a default
// declared as now()::text already carries a cast, and stripping it from
// one side only left the two permanently unequal.
//
// Anything more involved is compared as written. A database's printed form
// is stable across runs, so such a default still compares equal to itself,
// even where it does not compare equal to the way it was first spelled.
func defaultsEquivalent(a, b string) bool {
	return normalizeDefault(a) == normalizeDefault(b)
}

// normalizeDefault strips a whole-expression cast and any parentheses
// wrapping what is left, which between them account for how Postgres
// re-prints a default: now()::text comes back as (now())::text, and
// 'draft' as 'draft'::text.
func normalizeDefault(s string) string {
	return unwrapOuterParens(stripTrailingCast(s))
}

// stripTrailingCast removes a `::type` suffix applied to a whole
// expression, leaving one inside a literal alone.
func stripTrailingCast(s string) string {
	s = strings.TrimSpace(s)
	i := strings.LastIndex(s, "::")
	if i <= 0 || !castBalanced(s[:i]) {
		return s
	}
	// A cast names a type, so anything with a paren or quote after the ::
	// is not one.
	if rest := s[i+2:]; rest == "" || strings.ContainsAny(rest, "()'") {
		return s
	}
	return strings.TrimSpace(s[:i])
}

// castBalanced reports whether s leaves no parenthesis or quote open,
// which is what makes a following :: a cast of the whole expression rather
// than part of a literal.
func castBalanced(s string) bool {
	depth, inQuote := 0, false
	for _, r := range s {
		switch {
		case r == '\'':
			inQuote = !inQuote
		case inQuote:
		case r == '(':
			depth++
		case r == ')':
			depth--
		}
	}
	return depth == 0 && !inQuote
}
