package lsp

import (
	"strings"

	"github.com/tork-go/orm/gen/analyze"
)

// hover explains what is under the cursor. Every answer leads with the
// thing's own declaration in a code block, then the prose: what it
// generates, what column it becomes, what constraints it carries. That
// ordering matters because a hover is read in a glance, and the line
// the user is looking for is almost always the first one.
func (s *server) hover(f *folder, name string, pos Position) *Hover {
	doc := f.docs[name]
	sym := f.symbolAt(name, doc.offset(pos))
	text := f.describe(sym)
	if text == "" {
		return nil
	}
	rng := doc.rangeOf(sym.span)
	return &Hover{
		Contents: MarkupContent{Kind: "markdown", Value: text},
		Range:    &rng,
	}
}

func (f *folder) describe(sym symbol) string {
	switch sym.kind {
	case symModelName:
		if sym.model == nil {
			return ""
		}
		return code("model "+sym.model.Name) + describeModel(sym.model)

	case symEnumName, symEnumValue:
		if sym.enum == nil {
			return ""
		}
		if sym.kind == symEnumValue {
			return code(sym.enum.Name+"."+sym.name) + "Stored as `" + sym.name + "` in the " + sym.enum.DBName + " enum type."
		}
		return code("enum "+sym.enum.Name) + describeEnum(sym.enum)

	case symFieldName, symFieldRef:
		if sym.field == nil {
			return ""
		}
		return describeField(sym.field)

	case symTypeRef:
		switch {
		case sym.enum != nil:
			return code("enum "+sym.enum.Name) + describeEnum(sym.enum)
		case sym.target != nil:
			return code("model "+sym.target.Name) + describeModel(sym.target)
		}
		for _, e := range scalarEntries {
			if e.label == sym.name {
				return code(sym.name+"  "+e.detail) + e.doc
			}
		}
		return ""

	case symFieldAttrName:
		if e, ok := fieldAttrDoc(sym.name); ok {
			return code(e.detail) + e.doc
		}
		return ""

	case symBlockAttrName:
		if e, ok := blockAttrDoc(sym.name); ok {
			return code(e.detail) + e.doc
		}
		return ""
	}
	return ""
}

// describeField is the hover a user reads most: the field as written,
// then the column it becomes and everything attached to it.
func describeField(f *analyze.Field) string {
	var b strings.Builder
	b.WriteString(code(f.Name + " " + typeLabel(f)))
	if f.Doc != "" {
		b.WriteString(f.Doc)
		b.WriteString("\n\n")
	}
	if f.Relation != nil {
		b.WriteString(describeRelation(f))
		return b.String()
	}
	b.WriteString("Column `" + f.ColumnName + "`, scanning into `" + goTypeLabel(f) + "`.")

	var notes []string
	if f.IsID {
		notes = append(notes, "primary key")
	}
	if f.Unique {
		notes = append(notes, "unique")
	}
	if f.Indexed {
		notes = append(notes, "indexed")
	}
	if f.Optional {
		notes = append(notes, "nullable")
	}
	if f.SoftDelete {
		notes = append(notes, "soft delete marker")
	}
	if f.VarcharLen > 0 {
		notes = append(notes, "VARCHAR("+count(f.VarcharLen, "")+")")
	}
	if f.NumericPrecision > 0 {
		notes = append(notes, "NUMERIC")
	}
	if d := f.Default; d != nil {
		switch d.Kind {
		case analyze.DefaultAutoincrement:
			notes = append(notes, "generated identity")
		case analyze.DefaultUUID, analyze.DefaultGoFunc:
			notes = append(notes, "generated by "+goRefLabel(d.GoFunc))
		default:
			notes = append(notes, "default `"+d.SQL+"`")
		}
	}
	if len(notes) > 0 {
		b.WriteString("\n\n")
		b.WriteString(strings.Join(notes, ", "))
		b.WriteString(".")
	}
	return b.String()
}

func describeRelation(f *analyze.Field) string {
	r := f.Relation
	var b strings.Builder
	switch r.Kind {
	case analyze.RelBelongsTo:
		b.WriteString("Belongs to `" + r.Target.Name + "`")
	case analyze.RelHasOne:
		b.WriteString("Has one `" + r.Target.Name + "`")
	case analyze.RelHasMany:
		b.WriteString("Has many `" + r.Target.Name + "`")
	default:
		b.WriteString("Many to many with `" + r.Target.Name + "` through `" + r.Through.Name + "`")
	}
	if r.RelName != "" {
		b.WriteString(", named `" + r.RelName + "`")
	}
	b.WriteString(".")
	if len(r.Fields) > 0 && r.Kind != analyze.RelManyToMany {
		keys := make([]string, len(r.Fields))
		for i := range r.Fields {
			keys[i] = r.Fields[i].ColumnName + " to " + r.Target.TableName + "." + r.References[i].ColumnName
		}
		if r.Kind != analyze.RelBelongsTo {
			for i := range r.Fields {
				keys[i] = r.Target.TableName + "." + r.Fields[i].ColumnName + " to " + r.References[i].ColumnName
			}
		}
		b.WriteString("\n\nKey: " + strings.Join(keys, ", ") + ".")
	}
	if r.OnDelete != "" {
		b.WriteString("\n\nOn delete: " + r.OnDelete + ".")
	}
	return b.String()
}

// goTypeLabel is the Go type the generated row struct field will have,
// which is the detail a user hovering a field most often wants.
func goTypeLabel(f *analyze.Field) string {
	var base string
	switch f.Type.Kind {
	case analyze.TypeEnum:
		base = "string"
	case analyze.TypeJson:
		base = goRefLabel(f.GoType)
	default:
		for _, e := range scalarEntries {
			if e.label == f.Type.Kind.String() {
				base = e.detail
			}
		}
	}
	switch {
	case f.List && f.Optional:
		return "*[]" + base
	case f.List:
		return "[]" + base
	case f.Optional:
		return "*" + base
	}
	return base
}

func goRefLabel(ref analyze.GoTypeRef) string {
	if ref.ImportPath == "" {
		return ref.Name
	}
	return ref.ImportPath + "." + ref.Name
}

func code(s string) string { return "```tork\n" + s + "\n```\n\n" }
