package lsp_test

import (
	"strings"
	"testing"

	"github.com/tork-go/orm/lsp"
)

// richSchema exercises every shape a hover has something different to
// say about, so the descriptions can be checked in one session rather
// than a workspace per case.
const richSchema = `datasource db {
	provider = "postgres"
}

// Editorial state.
enum Status {
	draft
	published

	@@map("doc_status")
}

model Doc {
	id        Int       @id @default(autoincrement())
	title     String    @db.VarChar(120)
	price     Decimal   @db.Numeric(10, 2) @default(0)
	rate      Float     @default(1.5)
	live      Boolean   @default(true)
	key       Uuid      @unique @default(uuid())
	nonce     String    @default(go("myapp/ids.New"))
	tags      String[]
	scores    Int[]?
	meta      Json      @go.type("myapp/models.Meta")
	local     Json?     @go.type("Meta")
	status    Status    @default(draft)
	slug      String    @index
	deletedAt DateTime? @softDelete
	authorId  Int
	author    Author    @relation("DocAuthor", fields: [authorId], references: [id], onDelete: Cascade)
	labels    Label[]   @relation("DocLabels", through: DocLabel)

	@@check("price >= 0")
}

model Author {
	id      Int     @id @default(autoincrement())
	docs    Doc[]   @relation("DocAuthor")
	profile Profile @relation("AuthorProfile")
}

model Profile {
	id       Int    @id @default(autoincrement())
	authorId Int    @unique
	author   Author @relation("AuthorProfile", fields: [authorId], references: [id])
}

model Label {
	id   Int   @id @default(autoincrement())
	docs Doc[] @relation("DocLabels", through: DocLabel)
}

model DocLabel {
	docId   Int
	labelId Int
	doc     Doc   @relation(fields: [docId], references: [id])
	label   Label @relation(fields: [labelId], references: [id])

	@@id([docId, labelId])
}

model Composite {
	a Int
	b Int

	@@id([a, b])
}
`

// hoverAt asks for a hover and fails when there is none, since every
// case below is on something the server should have words for.
func hoverAt(t *testing.T, c *client, uri string, line, col int) string {
	t.Helper()
	var hover *lsp.Hover
	c.call("textDocument/hover", positionAt(uri, line, col), &hover)
	if hover == nil {
		t.Fatalf("no hover at %d:%d", line, col)
	}
	return hover.Contents.Value
}

func TestHover_DescribesEveryFieldShape(t *testing.T) {
	c := start(t)
	c.initialize()
	uri := workspace(t, map[string]string{"schema.tork": ""})("schema.tork")
	c.open(uri, richSchema)

	tests := []struct {
		name string
		line int
		col  int
		want []string
	}{
		{"an identity key", 13, 3, []string{"id Int", "`int`", "primary key", "generated identity"}},
		{"a sized string", 14, 3, []string{"title String", "VARCHAR", "Column `title`"}},
		{"a numeric column", 15, 3, []string{"price Decimal", "decimal.Decimal", "NUMERIC", "default `0`"}},
		{"a float default", 16, 3, []string{"rate Float", "float32", "default `1.5`"}},
		{"a boolean default", 17, 3, []string{"live Boolean", "bool", "default `TRUE`"}},
		{"a client generated uuid", 18, 3, []string{"key Uuid", "uuid.UUID", "unique", "generated by github.com/google/uuid.New"}},
		{"a client generated function", 19, 3, []string{"nonce String", "generated by myapp/ids.New"}},
		{"a list", 20, 3, []string{"tags String[]", "[]string"}},
		{"a nullable list", 21, 3, []string{"scores Int[]?", "*[]int", "nullable"}},
		{"a json column with an imported type", 22, 3, []string{"meta Json", "myapp/models.Meta"}},
		{"a json column with a local type", 23, 3, []string{"local Json?", "*Meta", "nullable"}},
		{"an enum column", 24, 3, []string{"status Status", "`string`", "default `'draft'`"}},
		{"an indexed column", 25, 3, []string{"slug String", "indexed"}},
		{"a soft delete marker", 26, 3, []string{"deletedAt DateTime?", "time.Time", "soft delete marker"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := hoverAt(t, c, uri, tt.line, tt.col)
			for _, want := range tt.want {
				if !strings.Contains(got, want) {
					t.Errorf("hover is missing %q:\n%s", want, got)
				}
			}
		})
	}
}

func TestHover_DescribesEveryRelationShape(t *testing.T) {
	c := start(t)
	c.initialize()
	uri := workspace(t, map[string]string{"schema.tork": ""})("schema.tork")
	c.open(uri, richSchema)

	tests := []struct {
		name string
		line int
		col  int
		want []string
	}{
		{"belongs to", 28, 3, []string{"Belongs to `Author`", "DocAuthor", "author_id to authors.id", "On delete: Cascade"}},
		{"many to many", 29, 3, []string{"Many to many with `Label`", "through `DocLabel`"}},
		{"has many", 36, 3, []string{"Has many `Doc`", "docs.author_id to id"}},
		{"has one", 37, 3, []string{"Has one `Profile`", "profiles.author_id to id"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := hoverAt(t, c, uri, tt.line, tt.col)
			for _, want := range tt.want {
				if !strings.Contains(got, want) {
					t.Errorf("hover is missing %q:\n%s", want, got)
				}
			}
		})
	}
}

func TestHover_DescribesDeclarations(t *testing.T) {
	c := start(t)
	c.initialize()
	uri := workspace(t, map[string]string{"schema.tork": ""})("schema.tork")
	c.open(uri, richSchema)

	tests := []struct {
		name string
		line int
		col  int
		want []string
	}{
		{"an enum name", 5, 7, []string{"enum Status", "Editorial state.", "doc_status", "draft, published"}},
		{"an enum value", 6, 2, []string{"Status.draft", "doc_status"}},
		{"a model with a composite key", 60, 8, []string{"model Composite", "key a, b"}},
		{"a model with a single key", 12, 8, []string{"model Doc", "Table docs", "key id"}},
		{"a block attribute inside an enum", 9, 4, []string{"@@map", "table name"}},
		{"a check attribute", 31, 4, []string{"@@check", "check constraint"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := hoverAt(t, c, uri, tt.line, tt.col)
			for _, want := range tt.want {
				if !strings.Contains(got, want) {
					t.Errorf("hover is missing %q:\n%s", want, got)
				}
			}
		})
	}
}

// Hovering something the server has nothing to say about answers null
// rather than an empty popup.
func TestHover_IsNullForUnknownConstructs(t *testing.T) {
	c := start(t)
	c.initialize()
	uri := workspace(t, map[string]string{"schema.tork": ""})("schema.tork")
	c.open(uri, "datasource db {\n\tprovider = \"postgres\"\n}\n\nmodel A {\n\tid Int @id @default(autoincrement()) @nope\n\tbad Zzz\n\t@@nope([id])\n}\n")

	for _, tt := range []struct {
		name string
		line int
		col  int
	}{
		{"an unknown attribute", 5, 40},
		{"an unresolvable type", 6, 7},
		{"an unknown block attribute", 7, 4},
		{"the datasource name", 0, 12},
		{"a string literal", 1, 15},
	} {
		t.Run(tt.name, func(t *testing.T) {
			var hover *lsp.Hover
			c.call("textDocument/hover", positionAt(uri, tt.line, tt.col), &hover)
			if hover != nil {
				t.Errorf("hover = %q, want null", hover.Contents.Value)
			}
		})
	}
}

func TestCompletion_FieldNamesComeFromTheEnclosingModel(t *testing.T) {
	c := start(t)
	c.initialize()
	uri := workspace(t, map[string]string{"schema.tork": ""})("schema.tork")
	c.open(uri, richSchema+"\nmodel Later {\n\talpha Int\n\tbeta String\n\t@@index([")

	lines := strings.Split(richSchema+"\nmodel Later {\n\talpha Int\n\tbeta String\n\t@@index([", "\n")
	var items []lsp.CompletionItem
	c.call("textDocument/completion", positionAt(uri, len(lines)-1, 10), &items)

	got := labels(items)
	for _, want := range []string{"alpha", "beta"} {
		if !contains(got, want) {
			t.Errorf("completion is missing %q; got %v", want, got)
		}
	}
	// Fields of other models must not leak in.
	if contains(got, "title") {
		t.Errorf("completion offered a field from another model: %v", got)
	}
	for _, it := range items {
		if it.Label == "alpha" && it.Detail != "alpha Int" {
			t.Errorf("detail = %q, want the column name and type", it.Detail)
		}
	}
}

// Relation fields have no column, so they are not offered where a
// column belongs.
func TestCompletion_FieldNamesExcludeRelations(t *testing.T) {
	c := start(t)
	c.initialize()
	uri := workspace(t, map[string]string{"schema.tork": ""})("schema.tork")
	text := richSchema + "\nmodel Later {\n\talpha Int\n\tdoc Doc @relation(\"L\", fields: [alpha], references: [id])\n\t@@index(["
	c.open(uri, text)

	lines := strings.Split(text, "\n")
	var items []lsp.CompletionItem
	c.call("textDocument/completion", positionAt(uri, len(lines)-1, 10), &items)
	if got := labels(items); contains(got, "doc") {
		t.Errorf("completion offered the relation field: %v", got)
	}
}

func TestCompletion_IsEmptyWhereNothingBelongs(t *testing.T) {
	c := start(t)
	c.initialize()
	uri := workspace(t, map[string]string{"schema.tork": ""})("schema.tork")
	c.open(uri, "model A {\n\tid Int @id @default(autoincrement())\n}\nmodel B extra\n")

	for _, tt := range []struct {
		name string
		line int
		col  int
	}{
		{"after a complete field", 1, 38},
		{"a top level line already past its first word", 3, 13},
	} {
		t.Run(tt.name, func(t *testing.T) {
			var items []lsp.CompletionItem
			c.call("textDocument/completion", positionAt(uri, tt.line, tt.col), &items)
			if len(items) != 0 {
				t.Errorf("completion = %v, want none", labels(items))
			}
		})
	}
}

func TestCompletion_InsideABlockAttributeArgumentThatTakesNoNames(t *testing.T) {
	c := start(t)
	c.initialize()
	uri := workspace(t, map[string]string{"schema.tork": ""})("schema.tork")
	c.open(uri, "model A {\n\tid Int @id @default(autoincrement())\n\t@@check(")

	var items []lsp.CompletionItem
	c.call("textDocument/completion", positionAt(uri, 2, 9), &items)
	if len(items) != 0 {
		t.Errorf("completion = %v, want none inside @@check", labels(items))
	}
}

// Completion for through: offers models, because that is what a join
// model reference is.
func TestCompletion_ThroughOffersModels(t *testing.T) {
	c := start(t)
	c.initialize()
	uri := workspace(t, map[string]string{"schema.tork": ""})("schema.tork")
	text := richSchema + "\nmodel Later {\n\txs Doc[] @relation(\"L\", through: "
	c.open(uri, text)

	lines := strings.Split(text, "\n")
	var items []lsp.CompletionItem
	c.call("textDocument/completion", positionAt(uri, len(lines)-1, len(lines[len(lines)-1])), &items)
	if got := labels(items); !contains(got, "DocLabel") {
		t.Errorf("completion is missing the join model; got %v", got)
	}
}

// The model named after through: is a type reference like any other,
// so it explains itself and can be jumped to.
func TestFeatures_OnTheThroughModel(t *testing.T) {
	c := start(t)
	c.initialize()
	uri := workspace(t, map[string]string{"schema.tork": ""})("schema.tork")
	c.open(uri, richSchema)

	got := hoverAt(t, c, uri, 29, 55)
	for _, want := range []string{"model DocLabel", "Table doc_labels"} {
		if !strings.Contains(got, want) {
			t.Errorf("hover is missing %q:\n%s", want, got)
		}
	}

	var locations []lsp.Location
	c.call("textDocument/definition", positionAt(uri, 29, 55), &locations)
	if len(locations) != 1 {
		t.Fatalf("locations = %+v, want the join model", locations)
	}
	if locations[0].Range.Start.Line != 51 {
		t.Errorf("line = %d, want 51", locations[0].Range.Start.Line)
	}
}
